### ISSUE TITLE
Build fails with --disable-usb

### ISSUE THREAD

**Issue by amon-sha** [rockowitz/ddcutil#183]
Version 1.0.0 and above fail to build when configured with --disable-usb flag:
```
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: ./.libs/libapp.a(query_sysenv_sysfs.o): in function `report_device_identification':
/tmp/ddcutil/src/app_sysenv/query_sysenv_sysfs.c:312: undefined reference to `devid_ensure_initialized'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /tmp/ddcutil/src/app_sysenv/query_sysenv_sysfs.c:314: undefined reference to `devid_get_pci_names'
```
The bug has been introduced in 84ad23091d8fc16b0ac83ee4f3840dde67c2ce6d

**Comment by rockowitz** [comment]
Fixed in branch 1.0.2-dev.  Thank you for the report.
