### PR TITLE
 Fix build with glibc 2.43 

### PR DESCRIPTION
**Pull request by ReillyBrogan**
From the glibc 2.43 release notes:

> In C23, for many functions a _Generic macro propagating the constness of a pointer parameter to the returned pointer has been added. This glibc release has implemented the change with C23 or _GNU_SOURCE enabled (i.e. -std=gnu17 won't fix everything). The change is expected to break some packages as (1) they assume the returned pointer is non-const or (2) they re-declare one of those functions without wrapping the function identifier in parentheses.

> For (1), the best fix is correctly retaining the constness when handling the returned pointer. If it's too difficult and you are pretty sure the code won't write through the returned pointer, you may also cast the constness away. For (2), simply add the parentheses. #undefing those macros can be used as a last resort.

### CODE REVIEW

**Comment by rockowitz** [comment]
Thank you for pointing out the impact of glibc 2.43.  I've applied your changes to branch 2.2.6-dev, or in the cases of hiddev_name_to_number() and rek_mkdir(), modifed the code to retain the const-ness of the function arguments.

**Comment by ReillyBrogan** [comment]
Did you perhaps not push that commit? I don't see it in github

**Comment by rockowitz** [comment]
You're quite right.  Pushed.

**Comment by ReillyBrogan** [comment]
I tried to build f81be6081d32ff9ddf63a840c6bde89ed11a10e3 and I'm getting the following error:
```
│B│ file_util.c:924:10: error: initializing 'char *' with an expression of type 'const char *' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
│B│   924 |    char *sep = strrchr(path, '/');
│B│       |          ^     ~~~~~~~~~~~~~~~~~~
│B│ 1 error generated.
```

**Comment by rockowitz** [comment]
I fixed the error  you reported in file_util.c and pushed the change to branch 2.2.6-dev.  I also reviewed all instances of the functions (strchr, etc.)  listed in the [glib 2.43 accouncement](https://sourceware.org/pipermail/libc-announce/2026/000052.html) so hopefully there are no more compatibility changes required for glibc 2.43.

**Comment by ReillyBrogan** [comment]
Alright I confirmed that 113bfd271d63a2ed74d6c6db3eae0ed30a66c55b now builds fine with glibc 2.43
