### ISSUE TITLE
make: deletes build_details.h before use

### ISSUE THREAD

**Issue by xiota** [rockowitz/ddcutil#443]
Fails to build.

```
Making install in base
make[2]: Entering directory '/home/main-builder/pkgwork/src/ddcutil/src/base'
echo "// Dummy include file to force rebuilding built_timestamp.c" > build_details.h
make  install-am
make[3]: Entering directory '/home/main-builder/pkgwork/src/ddcutil/src/base'
  CC       build_timestamp.lo
(src/base/Makefile) all-local
rm -fv build_details.h
removed 'build_details.h'
build_timestamp.c:9:10: fatal error: base/build_details.h: No such file or directory
    9 | #include "base/build_details.h"       // created by Makefile
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

`git bisect`:
```
git bisect start
# status: waiting for both good and bad commits
# good: [bbd5f6666a1d8b8537a70276077bca39376b39b5] eliminate misleading comment
git bisect good bbd5f6666a1d8b8537a70276077bca39376b39b5
# status: waiting for bad commit, 1 good commit known
# bad: [5b1fb8e53169acacda0058fd1a2ad545b08df0c3] workaround for $0 sometimes not set in build_detials.h recipie
git bisect bad 5b1fb8e53169acacda0058fd1a2ad545b08df0c3
# good: [3f628645547db5fa23fa504db1b27c1f70422613] use DBGF() for tracing
git bisect good 3f628645547db5fa23fa504db1b27c1f70422613
# bad: [9fe6576c4af3dcd5d20db150941689d7074022ef] detect if sysout/syserr appears to be redirected to syslog
git bisect bad 9fe6576c4af3dcd5d20db150941689d7074022ef
# bad: [f33da5507df197f70b000b23dab962e73d8d4a14] Create globals BUILD_DATE, BUILD_TIME that are updated on every build
git bisect bad f33da5507df197f70b000b23dab962e73d8d4a14
# first bad commit: [f33da5507df197f70b000b23dab962e73d8d4a14] Create globals BUILD_DATE, BUILD_TIME that are updated on every build
```

**Comment by rockowitz** [comment]
Fixed in commit b8efbf.
