### ISSUE TITLE
Release 2.2.4

### ISSUE THREAD

**Issue by rockowitz** [rockowitz/ddcutil#573]
**ddcutil** release 2.2.4 is now available as branch 2.2.4-release.

Detailed information about the changes can be found in file CHANGELOG.md in the source tree. Summary information is available on pages [Notes for Recent ddcutil Releases](https://www.ddcutil.com/release_notes_220) and [Shared Library Changes for Release 2.2.4](https://www.ddcutil.com/c_api_224) on the web site.

The new development branch is 2.2.5-dev.

**Comment by jpalus** [comment]
If you prefer I can create separate issue but note that 2.2.4 fails to build with gcc 15.2.0. It appears code makes assumptions about `va_list` implementation details while it shouldn't:
https://github.com/rockowitz/ddcutil/blob/90d75c75a9cb80178177191bdb832656efa8cd8f/src/util/report_util.c#L517
```console
report_util.c: In function 'xvrpt_vstring':
report_util.c:517:8: error: used struct type value where scalar is required
At top level:
cc1: note: unrecognized command-line option '-Wno-compound-token-split-by-macro' may have been intended to silence earlier diagnostics
```

**Comment by rockowitz** [comment]
@jpalus The bug should be fixed in branch 2.2.5-dev.  (See issue #574)

I will wait a few days to see if any other critical issues arise, then replace release 2.2.4 with 2.2.5.
